import { Office, Team, Match, User, Badge, FunStat } from './types';

export const OFFICES: Office[] = [
  {
    id: 'krakow',
    name: 'Kraków',
    city: 'Kraków',
    country: 'Poland',
    lat: 50.0647,
    lng: 19.9450,
    employeeCount: 450,
    totalPoints: 12450,
    avgPointsPerEmployee: 27.67,
  },
  {
    id: 'munich',
    name: 'München',
    city: 'München',
    country: 'Germany',
    lat: 48.1351,
    lng: 11.5820,
    employeeCount: 380,
    totalPoints: 10640,
    avgPointsPerEmployee: 28.00,
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    lat: -34.6037,
    lng: -58.3816,
    employeeCount: 320,
    totalPoints: 9280,
    avgPointsPerEmployee: 29.00,
  },
  {
    id: 'szczecin',
    name: 'Szczecin',
    city: 'Szczecin',
    country: 'Poland',
    lat: 53.4285,
    lng: 14.5528,
    employeeCount: 280,
    totalPoints: 7560,
    avgPointsPerEmployee: 27.00,
  },
  {
    id: 'wroclaw',
    name: 'Wrocław',
    city: 'Wrocław',
    country: 'Poland',
    lat: 51.1079,
    lng: 17.0385,
    employeeCount: 220,
    totalPoints: 6050,
    avgPointsPerEmployee: 27.50,
  },
  {
    id: 'tampere',
    name: 'Tampere',
    city: 'Tampere',
    country: 'Finland',
    lat: 61.4978,
    lng: 23.7610,
    employeeCount: 150,
    totalPoints: 4200,
    avgPointsPerEmployee: 28.00,
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    city: 'Ahmedabad',
    country: 'India',
    lat: 23.0225,
    lng: 72.5714,
    employeeCount: 200,
    totalPoints: 5400,
    avgPointsPerEmployee: 27.00,
  },
  {
    id: 'dublin',
    name: 'Dublin',
    city: 'Dublin',
    country: 'Ireland',
    lat: 53.3498,
    lng: -6.2603,
    employeeCount: 120,
    totalPoints: 3360,
    avgPointsPerEmployee: 28.00,
  },
  {
    id: 'bucharest',
    name: 'Bucharest',
    city: 'Bucharest',
    country: 'Romania',
    lat: 44.4268,
    lng: 26.1025,
    employeeCount: 180,
    totalPoints: 4860,
    avgPointsPerEmployee: 27.00,
  },
];

export const TEAMS: Record<string, Team> = {
  MEX: { id: 'MEX', name: 'Mexico', code: 'MEX', flag: '🇲🇽', group: 'A' },
  RSA: { id: 'RSA', name: 'South Africa', code: 'RSA', flag: '🇿🇦', group: 'A' },
  USA: { id: 'USA', name: 'USA', code: 'USA', flag: '🇺🇸', group: 'B' },
  GER: { id: 'GER', name: 'Germany', code: 'GER', flag: '🇩🇪', group: 'B' },
  ARG: { id: 'ARG', name: 'Argentina', code: 'ARG', flag: '🇦🇷', group: 'C' },
  POL: { id: 'POL', name: 'Poland', code: 'POL', flag: '🇵🇱', group: 'C' },
  BRA: { id: 'BRA', name: 'Brazil', code: 'BRA', flag: '🇧🇷', group: 'D' },
  FRA: { id: 'FRA', name: 'France', code: 'FRA', flag: '🇫🇷', group: 'D' },
  ENG: { id: 'ENG', name: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'E' },
  ESP: { id: 'ESP', name: 'Spain', code: 'ESP', flag: '🇪🇸', group: 'E' },
  POR: { id: 'POR', name: 'Portugal', code: 'POR', flag: '🇵🇹', group: 'F' },
  NED: { id: 'NED', name: 'Netherlands', code: 'NED', flag: '🇳🇱', group: 'F' },
  ITA: { id: 'ITA', name: 'Italy', code: 'ITA', flag: '🇮🇹', group: 'G' },
  BEL: { id: 'BEL', name: 'Belgium', code: 'BEL', flag: '🇧🇪', group: 'G' },
  URU: { id: 'URU', name: 'Uruguay', code: 'URU', flag: '🇺🇾', group: 'H' },
  CAN: { id: 'CAN', name: 'Canada', code: 'CAN', flag: '🇨🇦', group: 'H' },
};

export const MATCHES: Match[] = [
  {
    id: '1',
    homeTeam: TEAMS.MEX,
    awayTeam: TEAMS.RSA,
    venue: 'Estadio Azteca',
    city: 'Mexico City',
    date: new Date('2026-06-11T18:00:00Z'),
    stage: 'group',
    group: 'A',
    status: 'upcoming',
  },
  {
    id: '2',
    homeTeam: TEAMS.USA,
    awayTeam: TEAMS.GER,
    venue: 'SoFi Stadium',
    city: 'Los Angeles',
    date: new Date('2026-06-12T20:00:00Z'),
    stage: 'group',
    group: 'B',
    status: 'upcoming',
  },
  {
    id: '3',
    homeTeam: TEAMS.ARG,
    awayTeam: TEAMS.POL,
    venue: 'AT&T Stadium',
    city: 'Dallas',
    date: new Date('2026-06-12T22:00:00Z'),
    stage: 'group',
    group: 'C',
    status: 'upcoming',
  },
  {
    id: '4',
    homeTeam: TEAMS.BRA,
    awayTeam: TEAMS.FRA,
    venue: 'MetLife Stadium',
    city: 'New Jersey',
    date: new Date('2026-06-13T19:00:00Z'),
    stage: 'group',
    group: 'D',
    homeScore: 2,
    awayScore: 1,
    status: 'finished',
  },
  {
    id: '5',
    homeTeam: TEAMS.ENG,
    awayTeam: TEAMS.ESP,
    venue: 'Arrowhead Stadium',
    city: 'Kansas City',
    date: new Date('2026-06-13T21:00:00Z'),
    stage: 'group',
    group: 'E',
    homeScore: 1,
    awayScore: 1,
    status: 'live',
    minute: 67,
  },
  {
    id: '6',
    homeTeam: TEAMS.POR,
    awayTeam: TEAMS.NED,
    venue: 'Levi\'s Stadium',
    city: 'San Francisco',
    date: new Date('2026-06-14T20:00:00Z'),
    stage: 'group',
    group: 'F',
    status: 'upcoming',
  },
  {
    id: '7',
    homeTeam: TEAMS.ITA,
    awayTeam: TEAMS.BEL,
    venue: 'Mercedes-Benz Stadium',
    city: 'Atlanta',
    date: new Date('2026-06-14T22:00:00Z'),
    stage: 'group',
    group: 'G',
    status: 'upcoming',
  },
  {
    id: '8',
    homeTeam: TEAMS.URU,
    awayTeam: TEAMS.CAN,
    venue: 'BMO Field',
    city: 'Toronto',
    date: new Date('2026-06-15T19:00:00Z'),
    stage: 'group',
    group: 'H',
    status: 'upcoming',
  },
];

export const BADGES: Badge[] = [
  { id: 'oracle', name: 'The Oracle', description: '10 exact score predictions', icon: '🔮' },
  { id: 'streak5', name: 'Hot Streak', description: '5 correct predictions in a row', icon: '🔥' },
  { id: 'upset_king', name: 'Upset King', description: 'Predicted 3 underdog victories', icon: '👑' },
  { id: 'early_bird', name: 'Early Bird', description: 'Always predicts 24h before kickoff', icon: '🐦' },
  { id: 'optimist', name: 'The Optimist', description: 'Average predicted goals > 3.5', icon: '🌟' },
  { id: 'defensive', name: 'Defensive Mind', description: 'Predicts mostly 1-0 and 0-0', icon: '🛡️' },
  { id: 'tournament_winner', name: 'Champion Predictor', description: 'Predicted the World Cup winner', icon: '🏆' },
  { id: 'perfect_group', name: 'Perfect Group', description: 'All predictions correct in one group', icon: '💯' },
];

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Anna Kowalska',
    email: 'anna.kowalska@intive.com',
    officeId: 'krakow',
    points: 142,
    exactScores: 8,
    correctOutcomes: 24,
    missedPredictions: 2,
    currentStreak: 5,
    longestStreak: 7,
    badges: [BADGES[0], BADGES[1]],
    joinedAt: new Date('2026-05-01'),
  },
  {
    id: '2',
    name: 'Carlos Mendez',
    email: 'carlos.mendez@intive.com',
    officeId: 'buenos-aires',
    points: 138,
    exactScores: 9,
    correctOutcomes: 21,
    missedPredictions: 1,
    currentStreak: 3,
    longestStreak: 6,
    badges: [BADGES[2], BADGES[4]],
    joinedAt: new Date('2026-05-02'),
  },
  {
    id: '3',
    name: 'Thomas Mueller',
    email: 'thomas.mueller@intive.com',
    officeId: 'munich',
    points: 135,
    exactScores: 7,
    correctOutcomes: 23,
    missedPredictions: 3,
    currentStreak: 2,
    longestStreak: 5,
    badges: [BADGES[5]],
    joinedAt: new Date('2026-05-03'),
  },
];

export const FUN_STATS: FunStat[] = [
  {
    id: '1',
    title: 'Most Optimistic',
    description: 'Highest average goals predicted',
    value: 'Sarah Chen',
    userId: '5',
    userName: 'Sarah Chen',
    icon: '🌟',
    color: 'text-yellow-400',
  },
  {
    id: '2',
    title: 'Defensive Genius',
    description: 'Most 1-0 and 0-0 predictions',
    value: 'Thomas Mueller',
    userId: '3',
    userName: 'Thomas Mueller',
    icon: '🛡️',
    color: 'text-blue-400',
  },
  {
    id: '3',
    title: 'Upset King',
    description: 'Best at predicting underdog wins',
    value: 'Carlos Mendez',
    userId: '2',
    userName: 'Carlos Mendez',
    icon: '👑',
    color: 'text-purple-400',
  },
  {
    id: '4',
    title: 'Country Bias',
    description: 'Most optimistic about their home team',
    value: '🇦🇷 +2.3 goals',
    icon: '🎯',
    color: 'text-pink-400',
  },
  {
    id: '5',
    title: 'Last Minute Larry',
    description: 'Predicts within 1 hour of kickoff',
    value: 'Mike O\'Connor',
    userId: '8',
    userName: 'Mike O\'Connor',
    icon: '⏰',
    color: 'text-orange-400',
  },
  {
    id: '6',
    title: 'The Oracle',
    description: 'Highest exact score accuracy',
    value: 'Anna Kowalska (32%)',
    userId: '1',
    userName: 'Anna Kowalska',
    icon: '🔮',
    color: 'text-emerald-400',
  },
];
